### ISSUE TITLE
push rejected: FATAL: Can't find npm/node within meteor bundle

### ISSUE THREAD

**Issue by liorla** [AdmitHub/meteor-buildpack-horse#133] opened 2016-07-30 15:41 UTC
this start happening today...

the full error is:

remote: -----> Node.js app detected
remote: -----> Installing meteor
remote: curl: (3) Illegal characters found in URL
remote: /app/tmp/buildpacks/2a6b3cd8e392368665e034e859b6dd73daffd5ad6e476e155af3667bd21fdc765346a576e32db1450dd74e597a117a5b1c7e397b50e2d583268b716843bbe97a/bin/compile: 1: /app/tmp/buildpacks/2a6b3cd8eremote: /.meteor/meteor: not found
remote: -----> Meteor version: 
remote: -----> Checking if this meteor version supports --server-only
remote: /app/tmp/buildpacks/2a6b3cd8e392368665e034e859b6dd73daffd5ad6e476e155af3667bd21fdc765346a576e32db1450dd74e597a117a5b1c7e397b50e2d583268b716843bbe97a/bin/compile: 1: /app/tmp/buildpacks/2a6b3cd8eremote: /.meteor/meteor: not found
remote: -----> Attempting to remove android platform.
remote: /app/tmp/buildpacks/2a6b3cd8e392368665e034e859b6dd73daffd5ad6e476e155af3667bd21fdc765346a576e32db1450dd74e597a117a5b1c7e397b50e2d583268b716843bbe97a/bin/compile: 127: /app/tmp/buildpacks/2a6b3cdremote: /.meteor/meteor: not found
remote: -----> Moving on.
remote: FATAL: Can't find npm/node within meteor bundle. This is a bug. Please open an issue at https://github.com/AdmitHub/meteor-buildpack-horse.
remote:  !     Push rejected, failed to compile Node.js app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to trench-testing.

any ideas?

thank you!

**Comment by yourcelf** [comment] 2016-07-31 09:15
Could you share the contents of your `.meteor/release` file?

**Comment by astnt** [comment] 2016-07-31 11:25
looks like I have the same issue:
```
-----> Node.js app detected
-----> Meteor version: Meteor 1.4.0.1
-----> Checking if this meteor version supports --server-only
-----> Attempting to remove android platform.
While removing platforms:
error: android: platform is not in this project
-----> Moving on.
cp: cannot stat ‘/app/tmp/cache/1.2.1/.meteor/packages/meteor-tool/.1.4.0-1.csix32++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node\n/app/tmp/cache/1.2.1/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node’: No such file or directory
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```
`.meteor/release` METEOR@1.2.1

**Comment by astnt** [comment] 2016-07-31 11:51
fix from https://github.com/AdmitHub/meteor-buildpack-horse/issues/132 helped me:
```
heroku config:set BUILDPACK_CLEAR_CACHE=1
```

**Comment by liorla** [comment] 2016-07-31 13:48
setting the buildpack to previous version did it for me.

**Comment by yourcelf** [comment] 2016-07-31 16:39
OK, it looks like this issue is a duplicate of #132.  @liorla, set the buildpack back to the latest master, and also set `BUILDPACK_CLEAR_CACHE=1`.  Is there anything more you can tell me about any other process or changes to the meteor version you did that might have resulted in the buildpack installing some inconsistent versions of meteor for your app?

**Closed by yourcelf** 2016-07-31 16:39 UTC
