### ISSUE TITLE
Bug: PRELAUNCH_METEOR causes platform error

### ISSUE THREAD

**Issue by neil-s** [AdmitHub/meteor-buildpack-horse#70] opened 2016-03-01 18:55 UTC
#47 was either prematurely closed or has regressed due to a Meteor update. With the BUILDPACK_PRELAUNCH_METEOR config var set, and no mobile platforms added to my build, pushing to Heroku fails. Removing the config var makes it work again. The full error is below:

```
λ git push heroku master
Counting objects: 8, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (7/7), done.
Writing objects: 100% (8/8), 1.82 KiB | 0 bytes/s, done.
Total 8 (delta 2), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Fetching set buildpack https://github.com/AdmitHub/meteor-buildpack-horse.git... done
remote: -----> Node.js app detected
remote: -----> Installing node
remote: -----> Installing meteor
remote: Downloading Meteor distribution
remote: ######################################################################## 100.0%
remote:
remote: Meteor 1.2.1 has been installed in your home directory (~/.meteor).
remote:
remote: Now you need to do one of the following:
remote:
remote:   (1) Add "$HOME/.meteor" to your path, or
remote:   (2) Run this command as root:
remote:         cp "/tmp/buildpack20160301-158-1jetafv/meteor-akyt/.meteor/packages/meteor-tool/1.1.10/mt-os.linux.x86_64/scripts/admin/launch-meteor" /usr/bin/meteor
remote:
remote: Then to get started, take a look at 'meteor --help' or see the docs at
remote: docs.meteor.com.
remote: -----> Bundling bundle
remote: -----> Pre-launching Meteor to create packages assets and prevent bundling from failing
remote:
remote:
remote: While removing platforms:
remote: error: ios: platform is not in this project
remote: error: android: platform is not in this project
remote:
remote:
remote:  !     Push rejected, failed to compile Node.js app
remote:
remote: Verifying deploy...
remote:
remote: !       Push rejected to escalade-staging.
remote:
To https://git.heroku.com/escalade-staging.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/escalade-staging.git'
```

**Comment by yourcelf** [comment] 2016-03-22 15:45
Thanks for the report. Could you check and see if the issue is still present with the latest changes?  Better yet, could you help us out with a minimal meteor app that exhibits the bug that we can use in testing?

**Comment by yourcelf** [comment] 2016-04-16 22:02
I'm going to close this for now -- please reopen if you think there's an ongoing problem with the buildpack.

**Closed by yourcelf** 2016-04-16 22:02 UTC
Labels: need more info
