### ISSUE TITLE
How to skip build from zero when using with meteor and dokku.

### ISSUE THREAD

**Issue by Xiangshen-Meng** [AdmitHub/meteor-buildpack-horse#48] opened 2015-09-29 05:00 UTC
I am using meteor-buildpack-horse with dokku and meteor.
And it works perfectly when I push to dokku and deploy my app.

But every time I push to dokku, it build from installing node and meteor and it costs a lot of time.
Do you have any idea how can I skip the initial build?

**Comment by FransTwisk** [comment] 2015-11-06 14:25
I want the same thing. It's possible put that would mean changing the buildpack. I'm planning on creating one for faster deploys somewhere next week.

**Comment by yourcelf** [comment] 2015-11-06 16:58
Awesome, would love any PR's or suggestions for speeding things up.  Meteor's build process is slow -- and at least in the Heroku environment, I don't know of any way to accelerate that process yet.

**Comment by Xiangshen-Meng** [comment] 2015-11-07 04:12
@FransTwisk @yourcelf Awesome!! Waiting for the new pack!

**Comment by yourcelf** [comment] 2016-03-22 15:37
Closing as duplicate of the newer but slightly more clearly titled #64.

**Closed by yourcelf** 2016-03-22 15:37 UTC
