### ISSUE TITLE
Failed to deploy Meteor@1.4.2-beta.4

### ISSUE THREAD

**Issue by elledienne** [AdmitHub/meteor-buildpack-horse#146] opened 2016-09-21 08:05 UTC
I tried to deploy our app using the latest beta version of Meteor to Heroku using the builpack but it fails CURLing the package

`Retrying download in 5 seconds...`

Do you have any idea of what's the problem and how could be fixed?

**Comment by yourcelf** [comment] 2016-09-21 14:43
Sounds like the meteor install server was down briefly. Try again?

**Comment by elledienne** [comment] 2016-09-21 14:56
@yourcelf Actually still not working (and it's been like 24 hours since my first attempt)

I get always the same error

```
-----> Node.js app detected
----> Clearing cache dir.
-----> Installing meteor
Downloading Meteor distribution
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

**Comment by yourcelf** [comment] 2016-09-21 15:01
Can you turn on verbose output and try again?

From within the project, use:
 ```
heroku config:set BUILDPACK_VERBOSE=1
```
and then push to heroku again.

**Comment by elledienne** [comment] 2016-09-21 15:14
There it is

```
-----> Node.js app detected
+ dirname -- /app/tmp/buildpacks/2a6b3cd8e392368665e034e859b6dd73daffd5ad6e476e155af3667bd21fdc765346a576e32db1450dd74e597a117a5b1c7e397b50e2d583268b716843bbe97a/bin/compile
+ cd -P -- /app/tmp/buildpacks/2a6b3cd8e392368665e034e859b6dd73daffd5ad6e476e155af3667bd21fdc765346a576e32db1450dd74e597a117a5b1c7e397b50e2d583268b716843bbe97a/bin
+ cd ..
+ pwd -P
+ BUILDPACK_DIR=/app/tmp/buildpacks/2a6b3cd8e392368665e034e859b6dd73daffd5ad6e476e155af3667bd21fdc765346a576e32db1450dd74e597a117a5b1c7e397b50e2d583268b716843bbe97a
+ APP_CHECKOUT_DIR=/tmp/build_da87ce093bba78ee4940134bedb65d2e/DailyDeal-platform-16cdb3a9fdf39ba16b18d1518ec2b1214d73cb72
+ CACHE_DIR=/app/tmp/cache
+ [ -n 1 ]
+ echo ----> Clearing cache dir.
----> Clearing cache dir.
+ rm -rf /app/tmp/cache
+ APP_SOURCE_DIR=/tmp/build_da87ce093bba78ee4940134bedb65d2e/DailyDeal-platform-16cdb3a9fdf39ba16b18d1518ec2b1214d73cb72
+ [ -n  ]
+ [ ! -d /tmp/build_da87ce093bba78ee4940134bedb65d2e/DailyDeal-platform-16cdb3a9fdf39ba16b18d1518ec2b1214d73cb72/.meteor ]
+ [ ! -d /tmp/build_da87ce093bba78ee4940134bedb65d2e/DailyDeal-platform-16cdb3a9fdf39ba16b18d1518ec2b1214d73cb72/.meteor ]
+ cat /tmp/build_da87ce093bba78ee4940134bedb65d2e/DailyDeal-platform-16cdb3a9fdf39ba16b18d1518ec2b1214d73cb72/.meteor/release
+ sed -e s/METEOR@//
+ APP_RELEASE=1.4.2-beta.4
+ METEOR_DIR=/app/tmp/cache/1.4.2-beta.4
+ COMPILE_DIR_SUFFIX=.meteor/heroku_build
+ COMPILE_DIR=/tmp/build_da87ce093bba78ee4940134bedb65d2e/DailyDeal-platform-16cdb3a9fdf39ba16b18d1518ec2b1214d73cb72/.meteor/heroku_build
+ [ -z 1 ]
+ mkdir -p /tmp/build_da87ce093bba78ee4940134bedb65d2e/DailyDeal-platform-16cdb3a9fdf39ba16b18d1518ec2b1214d73cb72 /app/tmp/cache/1.4.2-beta.4
+ mkdir -p /tmp/build_da87ce093bba78ee4940134bedb65d2e/DailyDeal-platform-16cdb3a9fdf39ba16b18d1518ec2b1214d73cb72/.meteor/heroku_build /tmp/build_da87ce093bba78ee4940134bedb65d2e/DailyDeal-platform-16cdb3a9fdf39ba16b18d1518ec2b1214d73cb72/.meteor/heroku_build/bin /tmp/build_da87ce093bba78ee4940134bedb65d2e/DailyDeal-platform-16cdb3a9fdf39ba16b18d1518ec2b1214d73cb72/.meteor/heroku_build/lib
+ [ -z https://mobile.dailydeal.partners ]
+ [ -z https://mobile.dailydeal.partners ]
+ [ ! -e /app/tmp/cache/1.4.2-beta.4/.meteor/meteor ]
+ echo -----> Installing meteor
-----> Installing meteor
+ HOME=/app/tmp/cache/1.4.2-beta.4 /bin/sh
+ curl -sS https://install.meteor.com/?release=1.4.2-beta.4
Downloading Meteor distribution
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

**Comment by yourcelf** [comment] 2016-09-21 15:22
I'm pretty sure it's this: https://github.com/meteor/meteor/issues/7528 , though I've only seen that behavior with older beta releases before, and not the latest beta.

The root of the problem is that we're relying on https://install.meteor.com/?release=<version> to be reliable for all valid meteor versions, and it's not.

Assuming this is a correct diagnosis, the only quick fixes right now are to wait for Meteor to release 1.4.2 from beta, or to switch to a different beta or point release.

**Comment by elledienne** [comment] 2016-09-21 16:18
Too bad, I'm forced to use the version 1.4.2-beta.4 because of https://github.com/meteor/meteor/issues/7772.

It might be a bit off topic/stupid question, but if https://install.meteor.com/?release= is unreliable, why don't we use the GitHub releases (something like https://codeload.github.com/meteor/meteor/tar.gz/release/<METEOR_VERSION>) as source?

**Comment by yourcelf** [comment] 2016-09-21 17:11
We potentially could.  But then we'd have to duplicate the logic of the script served by https://install.meteor.com to do the actual installation.  This might be worth considering; though it would mean that if Meteor changed their install method (e.g. changed how they package releases) the buildpack would break.

To fix this without digging into Meteor internals as much, I think we need to just use plain `install.meteor.com` without the `?release` part.  There are two reasons we use the release part right now: (1) it makes the build faster (since whenever your target isn't the current stable release, you end up essentially installing meteor twice).  And (2), it makes it easier to find the version of `node` and `npm` that correspond to the target release within the meteor bundle -- not specifying `?release=` can result in two different versions of node existing within the meteor bundle (the current release's version, and your target release's version).

If we can solve (2) -- identifying the correct node version for your target release, even if there are multiple nodes within the meteor distribution -- then we can rely on heroku build caching to help solve (1).  Meteor provides a `meteor node` shortcut to execute the target release's version of node; but we need the _actual path_ to the binary, not to just execute it via the wrapper.  This is made more complicated by the fact that Meteor doesn't always include the exact current release's version number within the path that it stores node (e.g. if you install `1.4.2-beta.4`, the actual path to the node binary might be `1.4.1`).

One approach might be to list all the node binaries we can find within the meteor installation, parse out version numbers, parse the semantic version string, and identify the closest one that is less than or equal to the current release.  The complexity of that is why we haven't done it yet; it's error prone, but doable, and might resolve problems in #132 and #138 which make the cache unusable.

**Comment by yourcelf** [comment] 2016-09-21 17:23
We'll need to test it, but it looks like we might be able to use this:

```
meteor node -e "console.log(process.execPath)"
```

**Comment by elledienne** [comment] 2016-09-21 17:30
Uh, I see! It's actually much more complicated than I thought 😞.

Anyway, from my point of view it's not crucial to be able to deploy beta version, because I would try to avoid having a production app using a beta. That's just the theory though, in fact, as I'm experiencing right now, it could be very useful to be able to do it (and being able to rely on it) because betas might fix important incompatibility issues with other softwares/frameworks/whatever.

That said, I'm not sure if I can be really helpful with the development of such a feature, but I'd for sure help on testing it!

**Comment by bmustata** [comment] 2016-09-26 04:39
All the builds are failing on Heroku with this pack.

**Comment by ickyrr** [comment] 2016-09-26 09:48
@bmustata are you sure? I have deployed my meteor app just yesterday with this webpack. I just did a fork and removed the mongo lab add on. You refer to [this guide](https://meteorcoder.wordpress.com/2016/09/24/how-to-deploy-meteor-apps-with-heroku/). Maybe it'll help.

**Comment by yourcelf** [comment] 2016-09-26 19:57
@elledienne: Please try with the beta build; we've removed the dependence on `install.meteor.com/?release=<version>`.

You can set your project to use the beta release with:
```
heroku buildpacks:set https://github.com/AdmitHub/meteor-buildpack-horse.git#beta
```

**Comment by elledienne** [comment] 2016-09-27 06:53
Hey @yourcelf, thanks for the new beta! Unfortunately the build is failing again, tho.

```
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
````

Here you can find the complete log [http://pastebin.com/HL8TRXPD](http://pastebin.com/HL8TRXPD) (not posting it here cause it's really huge)

**Comment by yourcelf** [comment] 2016-09-27 13:43
Looks like you're missing an import named `qr-image`. Is it perhaps missing from package.json?

**Comment by elledienne** [comment] 2016-09-29 07:47
@yourcelf Ooops, embarrassing mistake :) I fixed the dependency and now it's working perfectly! Thank you!

**Comment by merlinpatt** [comment] 2016-10-27 16:46
@yourcelf Can confirm that this fails for Meteor 1.4.2 as well.

I upgraded to 1.4.2 and got this problem.

I then downgraded to 1.4.1 and was able to deploy successfully.

**Comment by rjakobsson** [comment] 2016-10-31 11:20
Same for me.

**Comment by rjakobsson** [comment] 2016-10-31 13:02
Are you relying on Blaze?
Could this be it?
***
"Blaze-related packages have been extracted to meteor/blaze, and the main meteor/meteor repository now refers to them via git submodules (see #7633). When running meteor from a checkout, you must now update these submodules by running

```
git submodule update --init --recursive
```
in the root directory of your meteor checkout."

from https://github.com/meteor/meteor/blob/devel/History.md

**Comment by rjakobsson** [comment] 2016-11-01 12:24
https://github.com/meteor/meteor/issues/7974 seems to be the issue.

**Comment by yourcelf** [comment] 2016-11-28 16:45
Closing now, as this seems to be an upstream issue unrelated to the buildpack, and upstream says it's fixed.

**Closed by yourcelf** 2016-11-28 16:45 UTC

**Comment by igor90007** [comment] 2017-01-26 17:17
my OS -- Windows 10. I had the same issue when tried to run "docker build ...". Reason - the file "release" in ".meteor" folder must be 15 byte or less.
