### ISSUE TITLE
1.4-beta.7: App is crashing after deploy

### ISSUE THREAD

**Issue by maxnowack** [AdmitHub/meteor-buildpack-horse#121] opened 2016-07-05 09:43 UTC
I've successfully deployed my app using meteor 1.4-beta.7 and the beta-branch.
But when heroku tries to start my app right after the deployment, I get the following exception in the logs:
````
2016-07-05T09:18:12.305369+00:00 heroku[web.1]: State changed from up to starting
2016-07-05T09:18:12.304574+00:00 heroku[web.1]: Restarting
2016-07-05T09:18:15.990103+00:00 heroku[web.1]: Process exited with status 143
2016-07-05T09:18:45.693829+00:00 heroku[web.1]: Starting process with command `HOME=.meteor-dist ./meteor-dist/.meteor/meteor node .meteor/heroku_build/app/main.js || HOME=.meteor-dist .meteor-dist/meteor-node .meteor/heroku_build/app/main.js`
2016-07-05T09:18:47.360377+00:00 app[web.1]:   throw new assert.AssertionError({
2016-07-05T09:18:47.360144+00:00 app[web.1]: assert.js:93
2016-07-05T09:18:47.360380+00:00 app[web.1]:         ^
2016-07-05T09:18:47.362448+00:00 app[web.1]: AssertionError: "undefined" === "function"
2016-07-05T09:18:47.362458+00:00 app[web.1]:     at wrapPathFunction (/app/.meteor/heroku_build/app/programs/server/mini-files.js:77:10)
2016-07-05T09:18:47.359915+00:00 app[web.1]: 
2016-07-05T09:18:47.362459+00:00 app[web.1]:     at Module._compile (module.js:456:26)
2016-07-05T09:18:47.362459+00:00 app[web.1]:     at Object.<anonymous> (/app/.meteor/heroku_build/app/programs/server/mini-files.js:108:24)
2016-07-05T09:18:47.362460+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:474:10)
2016-07-05T09:18:47.362462+00:00 app[web.1]:     at require (module.js:380:17)
2016-07-05T09:18:47.362461+00:00 app[web.1]:     at Module.require (module.js:364:17)
2016-07-05T09:18:47.362461+00:00 app[web.1]:     at Function.Module._load (module.js:312:12)
2016-07-05T09:18:47.362460+00:00 app[web.1]:     at Module.load (module.js:356:32)
2016-07-05T09:18:47.362462+00:00 app[web.1]:     at Object.<anonymous> (/app/.meteor/heroku_build/app/programs/server/boot.js:9:13)
2016-07-05T09:18:47.366217+00:00 app[web.1]: bash: .meteor-dist/meteor-node: No such file or directory
2016-07-05T09:18:47.362462+00:00 app[web.1]:     at Module._compile (module.js:456:26)
2016-07-05T09:18:48.167164+00:00 heroku[web.1]: Process exited with status 127
2016-07-05T09:18:48.183740+00:00 heroku[web.1]: State changed from starting to crashed
````

**Comment by yourcelf** [comment] 2016-07-07 03:51
This is the issue: https://github.com/meteor/meteor/issues/7338

The `meteor node` and `meteor npm` commands are not using the release's versions.  Perhaps this means that we can't (yet?) rely on these undocumented methods of obtaining the bundled node/npm.

(1.4-beta targets node v4, which is why you get the runtime error there -- a built-in that is not present in node v0.10 is being referenced.)

**Comment by yourcelf** [comment] 2016-07-07 03:53
Closing this as a duplicate of #120, please follow that one.

**Closed by yourcelf** 2016-07-07 03:53 UTC
