### ISSUE TITLE
Error when pushing to Heroku

### ISSUE THREAD

**Issue by sturoid** [AdmitHub/meteor-buildpack-horse#92] opened 2016-04-22 23:52 UTC
Thank you so much for the work you put into this. I'm getting this error when I try to deploy and I'm really lost on what the problem is:

remote: fibers@1.0.8 node_modules/fibers
remote: -----> Adding PATH environment
remote: -----> Running extras
remote: -----> Adding profile script to resolve MONGO_URL from mongolab addon
remote: -----> Installing phantomjs.
remote: bzip2: (stdin) is not a bzip2 file.
remote: tar: Child returned status 2
remote: tar: Error is not recoverable: exiting now
remote:
remote:  !     Push rejected, failed to compile Node.js app
remote:
remote: Verifying deploy...
remote:
remote: !	Push rejected to geosync-staging.
remote:

I'm on Meteor 1.3.2.2 and using npm for a lot of the packages. Do you have any idea what it could be? It seems to almost be at the end of the deployment when it happens. Thanks for your time.

**Comment by alexm0802** [comment] 2016-04-25 20:21
I have the same issue

**Comment by LobeTia** [comment] 2016-04-25 23:29
I get this error instead

`remote: -----> Bundling bundle
remote: -----> Checking if this meteor version supports --server-only
remote: npm ERR! install Couldn't read dependencies
remote: npm ERR! Linux 3.13.0-79-generic
remote: npm ERR! argv "/tmp/build_a232e938b969df95422862e3fc7547db/.meteor/heroku_build/bin/node" "/tmp/build_a232e938b969df95422862e3fc7547db/.meteor/heroku_build/bin/npm" "install"
remote: npm ERR! node v0.10.44
remote: npm ERR! npm  v2.15.0
remote: 
remote: npm ERR! Invalid version: "0.1"
remote: npm ERR! 
remote: npm ERR! If you need help, you may report this error at:
remote: npm ERR!     <https://github.com/npm/npm/issues>
remote: 
remote: npm ERR! Please include the following file with any support request:
remote: npm ERR!     /tmp/build_a232e938b969df95422862e3fc7547db/npm-debug.log
remote: 
remote:  !     Push rejected, failed to compile Node.js app
remote: 
remote: Verifying deploy...
remote: 
remote: !       Push rejected to idealith-developer.
remote: 
`

**Comment by yourcelf** [comment] 2016-04-25 23:42
@sturoid, @alexm0802: this issue is the same as #76. phantomjs is failing to download from bitbucket, and bzip2 is reporting an error when it tries to unpack it the failed download.  I'm closing this as a duplicate of #76 which we need to deal with.  #93 is a PR which could fix this.

@LobeTia: your issue is different -- it looks like you have an invalid version number specified in your package.json file.  If checking and fixing the package.json doesn't fix it, please open a new issue.

**Closed by yourcelf** 2016-04-25 23:42 UTC

**Comment by sturoid** [comment] 2016-04-26 16:41
@yourcelf thanks for the response. Do you have any idea when the PR will be merged?

**Comment by yourcelf** [comment] 2016-04-26 16:50
@sturoid I merged an alternate PR (that doesn't include the changes to node version) this morning. So you should be good to go!

**Comment by sturoid** [comment] 2016-04-26 16:55
You are a hero. So does Heroku pull the latest buildpack automatically when you do a heroku push, or do you have to remove and add the buildpack again?

**Comment by yourcelf** [comment] 2016-04-26 17:02
It uses the latest master if your buildpack is set to https://github.com/AdmitHub/meteor-buildpack-horse.git.  You can select a particular branch or commit with a hash on the URL, e.g. https://github.com/AdmitHub/meteor-buildpack-horse.git#devel or https://github.com/AdmitHub/meteor-buildpack-horse.git#23a141a5106e32b08ed893aac2781a3d1002094b , if you prefer to control that more.

**Comment by sturoid** [comment] 2016-04-26 17:08
Great. Thanks so much for your time.

**Comment by LobeTia** [comment] 2016-04-26 21:41
Yesterday I fixed my version typo (sorry) and I got the same error of @sturoid
Once you merged the PR is working like a charm, thank you for your time, awesome job!
