### ISSUE TITLE
Deployed but am getting an error

### ISSUE THREAD

**Issue by brianwphamSF** [AdmitHub/meteor-buildpack-horse#114] opened 2016-06-25 17:44 UTC
Can anybody help me please along with looking at my logs? I've been scratching my head and am unsure as to what's going on (Heroku newbie here). Localhost works fine.

```
2016-06-25T16:14:14.703910+00:00 app[web.1]: 
2016-06-25T16:14:14.704003+00:00 app[web.1]: events.js:72
2016-06-25T16:14:14.705174+00:00 app[web.1]:     at errnoException (child_process.js:1011:11)
2016-06-25T16:14:14.705183+00:00 app[web.1]:     at Process.ChildProcess._handle.onexit (child_process.js:802:34)
2016-06-25T16:14:15.721779+00:00 heroku[web.1]: Process exited with status 8
2016-06-25T16:14:15.734512+00:00 heroku[web.1]: State changed from up to crashed
2016-06-25T16:26:11.137920+00:00 heroku[web.1]: State changed from crashed to starting
2016-06-25T16:26:19.869510+00:00 heroku[web.1]: Starting process with command `.meteor/heroku_build/bin/node .meteor/heroku_build/app/main.js`
2016-06-25T16:26:28.428279+00:00 heroku[web.1]: State changed from starting to up
2016-06-25T16:26:28.770470+00:00 app[web.1]: sending update 0 times.
2016-06-25T16:26:28.782584+00:00 app[web.1]: events.js:72
2016-06-25T16:26:28.782454+00:00 app[web.1]: 
2016-06-25T16:26:28.782956+00:00 app[web.1]:         throw er; // Unhandled 'error' event
2016-06-25T16:26:28.784064+00:00 app[web.1]:     at Process.ChildProcess._handle.onexit (child_process.js:802:34)
2016-06-25T16:26:28.783116+00:00 app[web.1]:               ^
2016-06-25T16:26:28.784040+00:00 app[web.1]: Error: spawn ENOENT
2016-06-25T16:26:28.784055+00:00 app[web.1]:     at errnoException (child_process.js:1011:11)
2016-06-25T16:26:29.637984+00:00 heroku[web.1]: Process exited with status 8
2016-06-25T16:26:29.646914+00:00 heroku[web.1]: State changed from up to crashed
2016-06-25T16:39:21.603452+00:00 heroku[web.1]: State changed from crashed to starting
2016-06-25T16:39:29.793186+00:00 heroku[web.1]: Starting process with command `.meteor/heroku_build/bin/node .meteor/heroku_build/app/main.js`
2016-06-25T16:39:39.005112+00:00 heroku[web.1]: State changed from starting to up
2016-06-25T16:39:39.378423+00:00 app[web.1]: events.js:72
2016-06-25T16:39:39.360794+00:00 app[web.1]: sending update 0 times.
2016-06-25T16:39:39.378246+00:00 app[web.1]: 
2016-06-25T16:39:39.383801+00:00 app[web.1]:     at errnoException (child_process.js:1011:11)
2016-06-25T16:39:39.382717+00:00 app[web.1]:         throw er; // Unhandled 'error' event
2016-06-25T16:39:39.383786+00:00 app[web.1]: Error: spawn ENOENT
2016-06-25T16:39:39.382864+00:00 app[web.1]:               ^
2016-06-25T16:39:39.383814+00:00 app[web.1]:     at Process.ChildProcess._handle.onexit (child_process.js:802:34)
2016-06-25T16:39:40.476311+00:00 heroku[web.1]: Process exited with status 8
2016-06-25T16:39:40.520537+00:00 heroku[web.1]: State changed from up to crashed
2016-06-25T17:03:53.328957+00:00 heroku[web.1]: State changed from crashed to starting
2016-06-25T17:03:59.230606+00:00 heroku[web.1]: Starting process with command `.meteor/heroku_build/bin/node .meteor/heroku_build/app/main.js`
2016-06-25T17:04:04.684429+00:00 heroku[web.1]: State changed from starting to up
2016-06-25T17:04:05.256621+00:00 app[web.1]: events.js:72
2016-06-25T17:04:05.256508+00:00 app[web.1]: 
2016-06-25T17:04:05.256852+00:00 app[web.1]:         throw er; // Unhandled 'error' event
2016-06-25T17:04:05.257401+00:00 app[web.1]: Error: spawn ENOENT
2016-06-25T17:04:05.256868+00:00 app[web.1]:               ^
2016-06-25T17:04:05.250276+00:00 app[web.1]: sending update 0 times.
2016-06-25T17:04:05.257415+00:00 app[web.1]:     at errnoException (child_process.js:1011:11)
2016-06-25T17:04:05.257416+00:00 app[web.1]:     at Process.ChildProcess._handle.onexit (child_process.js:802:34)
2016-06-25T17:04:05.921468+00:00 heroku[web.1]: Process exited with status 8
2016-06-25T17:04:05.963150+00:00 heroku[web.1]: State changed from up to crashed
2016-06-25T17:05:43.472415+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=cvps.herokuapp.com request_id=f9d598e7-76d4-4011-b0f6-e06271885338 fwd="73.189.197.52" dyno= connect= service= status=503 bytes=
2016-06-25T17:17:41.482953+00:00 heroku[web.1]: State changed from crashed to starting
2016-06-25T17:17:48.739726+00:00 heroku[web.1]: Starting process with command `.meteor/heroku_build/bin/node .meteor/heroku_build/app/main.js`
2016-06-25T17:17:53.846988+00:00 heroku[web.1]: State changed from starting to up
2016-06-25T17:17:55.327015+00:00 heroku[web.1]: Process exited with status 8
2016-06-25T17:17:55.338414+00:00 heroku[web.1]: State changed from up to crashed
2016-06-25T17:23:17.824540+00:00 heroku[api]: Starting process with command `meteor run development` by brian.w.pham@gmail.com
2016-06-25T17:23:30.065789+00:00 heroku[run.9799]: Awaiting client
2016-06-25T17:23:30.097460+00:00 heroku[run.9799]: Starting process with command `meteor run development`
2016-06-25T17:23:30.282710+00:00 heroku[run.9799]: State changed from starting to up
2016-06-25T17:23:33.126417+00:00 heroku[run.9799]: Process exited with status 127
2016-06-25T17:23:33.151479+00:00 heroku[run.9799]: State changed from up to complete
2016-06-25T17:27:57.321969+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=cvps.herokuapp.com request_id=08b728f5-f92d-47fd-8977-12162487c30c fwd="73.189.197.52" dyno= connect= service= status=503 bytes=
2016-06-25T17:27:57.959560+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=cvps.herokuapp.com request_id=57505e4d-2464-46da-9794-8b85f589f2ca fwd="73.189.197.52" dyno= connect= service= status=503 bytes=
2016-06-25T17:28:02.332314+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=cvps.herokuapp.com request_id=eec1383f-9a8a-4ebc-9849-e1a32ac3d5f4 fwd="73.189.197.52" dyno= connect= service= status=503 bytes=
2016-06-25T17:28:03.273920+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=cvps.herokuapp.com request_id=090469ec-851b-4591-92b6-34836293992d fwd="73.189.197.52" dyno= connect= service= status=503 bytes=
2016-06-25T17:33:51.963556+00:00 heroku[web.1]: State changed from crashed to starting
2016-06-25T17:33:58.516048+00:00 heroku[web.1]: Starting process with command `.meteor/heroku_build/bin/node .meteor/heroku_build/app/main.js`
2016-06-25T17:34:04.119676+00:00 heroku[web.1]: State changed from starting to up
2016-06-25T17:34:04.685076+00:00 app[web.1]: sending update 0 times.
2016-06-25T17:34:04.708559+00:00 app[web.1]: events.js:72
2016-06-25T17:34:04.709541+00:00 app[web.1]:     at Process.ChildProcess._handle.onexit (child_process.js:802:34)
2016-06-25T17:34:04.708917+00:00 app[web.1]:               ^
2016-06-25T17:34:04.709531+00:00 app[web.1]: Error: spawn ENOENT
2016-06-25T17:34:04.708905+00:00 app[web.1]:         throw er; // Unhandled 'error' event
2016-06-25T17:34:04.708446+00:00 app[web.1]: 
2016-06-25T17:34:04.709540+00:00 app[web.1]:     at errnoException (child_process.js:1011:11)
2016-06-25T17:34:05.597348+00:00 heroku[web.1]: Process exited with status 8
2016-06-25T17:34:05.607495+00:00 heroku[web.1]: State changed from up to crashed
2016-06-25T17:38:09.158150+00:00 heroku[slug-compiler]: Slug compilation started
2016-06-25T17:38:09.158160+00:00 heroku[slug-compiler]: Slug compilation finished
2016-06-25T17:38:08.933171+00:00 heroku[api]: Deploy 16a0189 by brian.w.pham@gmail.com
2016-06-25T17:38:08.933280+00:00 heroku[api]: Release v14 created by brian.w.pham@gmail.com
2016-06-25T17:38:09.236968+00:00 heroku[web.1]: State changed from crashed to starting
2016-06-25T17:38:19.298087+00:00 heroku[web.1]: Starting process with command `.meteor/heroku_build/bin/node .meteor/heroku_build/app/main.js`
2016-06-25T17:38:29.679185+00:00 heroku[web.1]: State changed from starting to up
2016-06-25T17:38:30.265273+00:00 app[web.1]: sending update 0 times.
2016-06-25T17:38:30.306389+00:00 app[web.1]:         throw er; // Unhandled 'error' event
2016-06-25T17:38:30.305848+00:00 app[web.1]: 
2016-06-25T17:38:30.305945+00:00 app[web.1]: events.js:72
2016-06-25T17:38:30.309206+00:00 app[web.1]:     at Process.ChildProcess._handle.onexit (child_process.js:802:34)
2016-06-25T17:38:30.306396+00:00 app[web.1]:               ^
2016-06-25T17:38:30.309193+00:00 app[web.1]: Error: spawn ENOENT
2016-06-25T17:38:30.309205+00:00 app[web.1]:     at errnoException (child_process.js:1011:11)
2016-06-25T17:38:31.412487+00:00 heroku[web.1]: Process exited with status 8
2016-06-25T17:38:31.424601+00:00 heroku[web.1]: State changed from up to crashed
2016-06-25T17:38:30.228993+00:00 heroku[router]: at=info method=GET path="/" host=cvps.herokuapp.com request_id=e526f4c5-81b8-4c2f-a760-18a7c530bb62 fwd="73.189.197.52" dyno=web.1 connect=1ms service=75ms status=200 bytes=1069
2016-06-25T17:38:32.752959+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/ef59e8998d76fb2b9c0d0d6a54eaba33ad7f7b23.css?meteor_css_resource=true" host=cvps.herokuapp.com request_id=babe6dfe-b98a-4bca-91f1-278626f080fb fwd="73.189.197.52" dyno= connect= service= status=503 bytes=
2016-06-25T17:38:32.474117+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/ef59e8998d76fb2b9c0d0d6a54eaba33ad7f7b23.css?meteor_css_resource=true" host=cvps.herokuapp.com request_id=550636cf-be90-4200-ba6e-3d14d2e2cca8 fwd="73.189.197.52" dyno=web.1 connect=1ms service= status=503 bytes=
2016-06-25T17:38:35.822303+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/7cba63d9bb68a0ada6512396a64a652c2dae415e.js?meteor_js_resource=true" host=cvps.herokuapp.com request_id=a858f7a8-6c6b-4fb4-9b5e-f992e97a1324 fwd="73.189.197.52" dyno=web.1 connect=5000ms service= status=503 bytes=
2016-06-25T17:38:35.776050+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/454ac837c512b68da6b50b2998ab1dbfab84d819.css?meteor_css_resource=true" host=cvps.herokuapp.com request_id=3b21cad4-3766-4aa9-88f6-c71e671e4e11 fwd="73.189.197.52" dyno=web.1 connect=5000ms service= status=503 bytes=
2016-06-25T17:38:36.276520+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=cvps.herokuapp.com request_id=a0bf13ce-290e-424a-b93b-f16ad63bdb09 fwd="73.189.197.52" dyno= connect= service= status=503 bytes=
2016-06-25T17:38:42.073477+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=cvps.herokuapp.com request_id=15ab1534-4e3c-4694-9b08-f5245d274381 fwd="73.189.197.52" dyno= connect= service= status=503 bytes=
2016-06-25T17:38:42.590292+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=cvps.herokuapp.com request_id=d5adbcb4-598e-4b6c-99f2-9950371e7b49 fwd="73.189.197.52" dyno= connect= service= status=503 bytes=
2016-06-25T17:40:20.095216+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=cvps.herokuapp.com request_id=2f1d66ab-85bc-4ca6-a27b-12cc347f162c fwd="73.189.197.52" dyno= connect= service= status=503 bytes=
2016-06-25T17:40:20.616367+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=cvps.herokuapp.com request_id=6c3e8fe2-92f3-4be2-898f-851b10991959 fwd="73.189.197.52" dyno= connect= service= status=503 bytes=
```

Thanks!

**Comment by yourcelf** [comment] 2016-06-28 16:24
Not sure; `ENOENT` generally means a file or directory can't be found.  The most common source of errors like this is not checking all of the required files in to git.

Can you share the source code to your app?  Hard to debug otherwise.

**Comment by yourcelf** [comment] 2016-07-29 17:27
Without further info, I'm going to close this issue now.  Please reopen if you think the problem is a bug with the buildpack and can provide more detail.

**Closed by yourcelf** 2016-07-29 17:27 UTC
