### ISSUE TITLE
process.env.METEOR_SHELL_DIR

### ISSUE THREAD

**Issue by romainkoenig** [AdmitHub/meteor-buildpack-horse#157] opened 2016-12-12 14:33 UTC
##### Type of problem

 - Runtime problem after the build succeeds

##### Summary

A process.env disappear, and I am searching an equivalent.
I use this variable : 
````js
const dirPath = `${process.env.METEOR_SHELL_DIR}/../../../public`;
`````
To access a PDF in my public folder. ( I cannot access it normally since I use it with meteor picker ).
It works well in local but not when I push my app on herolu, so I am wondering if the package set a variable to use to access the public lib/
##### Contents of `.meteor/release`

```
METEOR@1.4.1.1
```

##### Buildpack version

```
?
```

##### Logs

By printings env var I saw : 
```
14:12:37.781834+00:00 app[web.1]: { BUILDPACK_CLEAR_CACHE: '1',
14:12:37.781848+00:00 app[web.1]:   LD_LIBRARY_PATH: ':/app/.meteor/heroku_build/lib',
14:12:37.781849+00:00 app[web.1]:   ENV: 'preproduction',
14:12:37.781849+00:00 app[web.1]:   DYNO: 'web.1',
14:12:37.781850+00:00 app[web.1]:   PATH: '...',
14:12:37.781870+00:00 app[web.1]:   METEOR_SETTINGS: '{...}',
14:12:37.781871+00:00 app[web.1]:   PWD: '/app',
14:12:37.781872+00:00 app[web.1]:   MONGO_URL: '...',
14:12:37.781873+00:00 app[web.1]:   TZ: 'Europe/Paris',
2016-12-12T14:12:37.781874+00:00 app[web.1]:   ROOT_URL: 'https://myapp.herokuapp.com',
2016-12-12T14:12:37.781875+00:00 app[web.1]:   SHLVL: '1',
2016-12-12T14:12:37.781875+00:00 app[web.1]:   HOME: '/app',
2016-12-12T14:12:37.781876+00:00 app[web.1]:   PORT: 'XXXX',
2016-12-12T14:12:37.781877+00:00 app[web.1]:   _: '.meteor/heroku_build/bin/node',
2016-12-12T14:12:37.781878+00:00 app[web.1]:   APP_ID: '...',
2016-12-12T14:12:37.781878+00:00 app[web.1]:   NODE_ENV: 'production',
2016-12-12T14:12:37.781879+00:00 app[web.1]:   TEST_METADATA: '{}',
2016-12-12T14:12:37.781880+00:00 app[web.1]:   MAIL_URL: '...' }
```
I only see HOME or PWD which may be interesting ? 

##### Deployment target
Heroku

**Comment by yourcelf** [comment] 2017-03-14 18:25
When you build your app on Heroku, it creates a built slug which does not have the same directory structure as your project directory.  To see what it looks like, run `meteor build --directory=/tmp/my-app/`, and then look at the contents of `/tmp/my-app/`.  It likely will not have a `public` folder; instead the contents might be somewhere like `programs/web.browser/app/`.

It might be easier to host your assets elsewhere like on s3 and then just access by URL rather than negotiating meteor's path munging.

Closing this now, as it's not a bug with the buildpack.  Hope you've found or are able to find a solution.

**Closed by yourcelf** 2017-03-14 18:25 UTC
