### ISSUE TITLE
Compression size 

### ISSUE THREAD

**Issue by santiq** [AdmitHub/meteor-buildpack-horse#125] opened 2016-07-26 16:44 UTC
I'm using the branch `beta` for deploying my Meteor 1.4 app

But the slug size exces the maximum allowed by heroku

```
-----> Discovering process types
       Procfile declares types     -> (none)
       Default types for buildpack -> web
-----> Compressing...
 !     Compiled slug size: 330.6M is too large (max is 300M).
 !     See: http://devcenter.heroku.com/articles/slug-size
 !     Push failed
```

This not happens with  the branch `master`, but I need beta because some npm dependencies _(like angular-translate)_ needs `node  4.4.7`

**Comment by jamiter** [comment] 2016-07-27 13:54
Also experiencing this. Size went from 130M to 336M. Haven't found out why yet.

**Comment by yourcelf** [comment] 2016-07-27 14:00
I believe the problem is that the beta branch switches to `meteor npm` and `meteor node` as the method for finding/invoking node rather than downloading its own separate node's.  But to facilitate that, we need to include the meteor distribution itself in the built slug alongside the compiled app.  And meteor itself is *large*.

We'll likely need to change this strategy to something else -- either locating and extracting the node binary from within the meteor distribution, or downloading a fresh copy based on version number or something.

**Comment by jsantana90** [comment] 2016-07-28 14:55
Just deployed with the beta branch of buildpack-horse in heroku with a meteor version 1.4 app

It went from `Done: 32.8M` to `Done: 213.6M`

**Comment by yourcelf** [comment] 2016-07-28 20:13
Slug size problems should be fixed in the latest #beta version.  Now just copying the `node` binary onto the finished slug, rather than copying the entire meteor world.  Please try it out.

**Comment by santiq** [comment] 2016-07-28 20:38
Yes! Now it works!

```
-----> Compressing...
       Done: 101.1M
-----> Launching...

```

Thanks!

**Comment by jsantana90** [comment] 2016-07-29 03:09
yep, it's working as well now:

```
remote: -----> Compressing...
remote:        Done: 34.1M
remote: -----> Launching...
```

**Comment by yourcelf** [comment] 2016-07-29 17:19
Alright, #130 is merged, you should be able to run this off master now.

**Closed by yourcelf** 2016-07-29 17:19 UTC

**Comment by jsantana90** [comment] 2016-07-29 20:02
I'm having trouble now with a Meteor version 1.2

```
-----> Node.js app detected
-----> Installing meteor
Downloading Meteor distribution
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

Just happen today :(

**Comment by yourcelf** [comment] 2016-07-29 20:10
@jsantana90 Please open as a new issue.

I've seen this when Meteor no longer correctly hosts the files depended on by the installation script for the version that you request.  What are the exact contents of `.meteor/release` for your project?

**Comment by jsantana90** [comment] 2016-07-29 20:12
I've opened a new issue #132

**Comment by totoide** [comment] 2016-08-24 01:44
Hi @yourcelf ,

Thanks for this fabulous package! I see in this issue that you've fixed the slug size issues and merged to master but I'm still having a problem.

My slug size went from 43.2M to 330.4M and won't build on Heroku since the max is 300M. I've made a couple of bug fixes and updated from 1.4.0.1 to METEOR@1.4.1 but nothing that would cause such a huge jump. I set the BUILDPACK_CLEAR_CACHE=1 and that didn't work.

Is there a way to verify my build is using the latest version of the buildpack or another way to troubleshoot?

Many thanks.

**Comment by yourcelf** [comment] 2016-08-24 20:06
@totoide, what is the output of `heroku buildpacks` within your project?

**Comment by totoide** [comment] 2016-08-24 20:13
@yourcelf The output is https://github.com/AdmitHub/meteor-buildpack-horse.git

I mostly don't know what I'm doing so thank you for your help.

**Comment by yourcelf** [comment] 2016-08-24 20:16
@totoide OK, looks like you are using the latest.  I don't know why you're still having that trouble. Any chance you can share the source code to your project?  Or if not that, try creating a minimal project that still exhibits the problem -- try starting with an empty project that has the same dependencies and meteor version.

**Comment by ziadrida** [comment] 2019-04-25 15:24
Did anyone resolve the issue of  "Downloading Meteor distribution" or simply meteor increasing slug size when deploying to heroku by over 250 MB?!

**Comment by santiq** [comment] 2019-04-25 15:50
oh my god this is so _vintage_
